id: A63666B26
title: Prayer for the Long Life of Dzogchen Rinpoche
type: translation
pechas:
- I68336188
- I71FC1F81
- I4D4AF7FF
- I02CE1E79
source_metadata:
  languages:
  - en
  - es
  - nl
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:53:08.719003
  last_modified_at: 2023-01-04 11:53:08.719015
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I68336188/1F68: E95A
  I71FC1F81/B917: E95A
  I4D4AF7FF/D1CA: E95A
  I02CE1E79/9ACB: E95A
